name: MinePlugin
version: @version@
main: me.mani123.mineplugin.MinePlugin
api-version: 1.16
authors: [ mani123 ]
description: Minecraft plugin
website: site.ru
commands:
  home:
    description: Home commands
    usage: /<command> [set/tp/reload/del]
    default: true
    aliases:
      - дом
      - домой