name: MinePlugin
version: @version@
main: me.mani123.mineplugin.MinePlugin
api-version: 1.16
authors: [ mani123 ]
description: Minecraft plugin
website: site.ru
commands:
  home:
    description: teleport to home
    aliases:
      - дом
      - домой
  sethome:
    description: set location the home
    aliases:
      - сетдом
      - устдом